### PR TITLE
Add MirahezeMagic global interface messages for Trust and Safety

### PR DESCRIPTION
**Pull request by dmehus**
Per discussion with @OwenBaines. Group page isn't live yet, but will be on or the day before May 1st

### CODE REVIEW

**Comment by Universal-Omega** [comment]
Should probably be added to qqq.json also.

**Comment by dmehus** [comment]
> Should probably be added to qqq.json also.

@Universal-Omega Yeah, I did that, but I have trouble with adding additional files in my fork to a PR I hadn't yet started. It always wants to commit the second one directly to my master branch, and I don't see where my patch-1 is in the options.

**Comment by dmehus** [comment]
@Reception123 Thanks for merging this PR today, but when I visit [this interface message](https://publictestwiki.com/wiki/MediaWiki:Grouppage-trustandsafety), as just one example, it's still a redlink, and not a bluelink. Is there perhaps a maintenance script you might need to run to refresh the MirahezeMagic interface messages?

**Comment by Universal-Omega** [comment]
@dmehus The extension wasn't updated yet, or RebuildLC run.

**Comment by dmehus** [comment]
> @dmehus The extension wasn't updated yet, or RebuildLC run.

What do you mean the extension was not updated? And yeah, RebuildLC is the script I was thinking of.

**Comment by Universal-Omega** [comment]
> > @dmehus The extension wasn't updated yet, or RebuildLC run.
> 
> What do you mean the extension was not updated? And yeah, RebuildLC is the script I was thinking of.

MirahezeMagic wasn't updated, I don't think.

**Comment by dmehus** [comment]
> > > @dmehus The extension wasn't updated yet, or RebuildLC run.
> > 
> > 
> > What do you mean the extension was not updated? And yeah, RebuildLC is the script I was thinking of.
> 
> MirahezeMagic wasn't updated, I don't think.

Oh, how is that updated? Do you mean I missed doing another commit, or is there a second maintenance script that needs to be run?

**Comment by Universal-Omega** [comment]
> > > > @dmehus The extension wasn't updated yet, or RebuildLC run.
> > > 
> > > 
> > > What do you mean the extension was not updated? And yeah, RebuildLC is the script I was thinking of.
> > 
> > 
> > MirahezeMagic wasn't updated, I don't think.
> 
> Oh, how is that updated? Do you mean I missed doing another commit, or is there a second maintenance script that needs to be run?

MirahezeMagic is an extension, it needs updated like all other extensions.

**Comment by dmehus** [comment]
> > > > > @dmehus The extension wasn't updated yet, or RebuildLC run.
> > > > 
> > > > 
> > > > What do you mean the extension was not updated? And yeah, RebuildLC is the script I was thinking of.
> > > 
> > > 
> > > MirahezeMagic wasn't updated, I don't think.
> > 
> > 
> > Oh, how is that updated? Do you mean I missed doing another commit, or is there a second maintenance script that needs to be run?
> 
> MirahezeMagic is an extension, it needs updated like all other extensions.

But we're just updating the json file. Can you fill me in on the missing link in my thought process as I'm not familiar with the process that needs to be updated?

**Comment by Universal-Omega** [comment]
> > > > > > @dmehus The extension wasn't updated yet, or RebuildLC run.
> > > > > 
> > > > > 
> > > > > What do you mean the extension was not updated? And yeah, RebuildLC is the script I was thinking of.
> > > > 
> > > > 
> > > > MirahezeMagic wasn't updated, I don't think.
> > > 
> > > 
> > > Oh, how is that updated? Do you mean I missed doing another commit, or is there a second maintenance script that needs to be run?
> > 
> > 
> > MirahezeMagic is an extension, it needs updated like all other extensions.
> 
> But we're just updating the json file. Can you fill me in on the missing link in my thought process as I'm not familiar with the process that needs to be updated?

Yes it's the json file, but still MirahezeMagic submodule still needs updated in miraheze/mediawiki repo for changes to be live.

**Comment by dmehus** [comment]
> > > > > > > @dmehus The extension wasn't updated yet, or RebuildLC run.
> > > > > > 
> > > > > > 
> > > > > > What do you mean the extension was not updated? And yeah, RebuildLC is the script I was thinking of.
> > > > > 
> > > > > 
> > > > > MirahezeMagic wasn't updated, I don't think.
> > > > 
> > > > 
> > > > Oh, how is that updated? Do you mean I missed doing another commit, or is there a second maintenance script that needs to be run?
> > > 
> > > 
> > > MirahezeMagic is an extension, it needs updated like all other extensions.
> > 
> > 
> > But we're just updating the json file. Can you fill me in on the missing link in my thought process as I'm not familiar with the process that needs to be updated?
> 
> Yes it's the json file, but still MirahezeMagic submodule still needs updated in miraheze/mediawiki repo for changes to be live.

Oh, interesting, and we do that _every_ time we add or delete a MirahezeMagic interface message/override? If _so_, I wasn't aware of that; I was only aware of the RebuildLC maintenance script part. Perhaps @Reception123 can fill me in more on the technicals of the process when he gets up. Anyway, thanks! :)

**Comment by Universal-Omega** [comment]
> > > > > > > > @dmehus The extension wasn't updated yet, or RebuildLC run.
> > > > > > > 
> > > > > > > 
> > > > > > > What do you mean the extension was not updated? And yeah, RebuildLC is the script I was thinking of.
> > > > > > 
> > > > > > 
> > > > > > MirahezeMagic wasn't updated, I don't think.
> > > > > 
> > > > > 
> > > > > Oh, how is that updated? Do you mean I missed doing another commit, or is there a second maintenance script that needs to be run?
> > > > 
> > > > 
> > > > MirahezeMagic is an extension, it needs updated like all other extensions.
> > > 
> > > 
> > > But we're just updating the json file. Can you fill me in on the missing link in my thought process as I'm not familiar with the process that needs to be updated?
> > 
> > 
> > Yes it's the json file, but still MirahezeMagic submodule still needs updated in miraheze/mediawiki repo for changes to be live.
> 
> Oh, interesting, and we do that _every_ time we add or delete a MirahezeMagic interface message/override? If _so_, I wasn't aware of that; I was only aware of the RebuildLC maintenance script part. Perhaps @Reception123 can fill me in more on the technicals of the process when he gets up. Anyway, thanks! :)

Yep it's always been done like that.

**Comment by dmehus** [comment]
> > > > > > > > > @dmehus The extension wasn't updated yet, or RebuildLC run.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > What do you mean the extension was not updated? And yeah, RebuildLC is the script I was thinking of.
> > > > > > > 
> > > > > > > 
> > > > > > > MirahezeMagic wasn't updated, I don't think.
> > > > > > 
> > > > > > 
> > > > > > Oh, how is that updated? Do you mean I missed doing another commit, or is there a second maintenance script that needs to be run?
> > > > > 
> > > > > 
> > > > > MirahezeMagic is an extension, it needs updated like all other extensions.
> > > > 
> > > > 
> > > > But we're just updating the json file. Can you fill me in on the missing link in my thought process as I'm not familiar with the process that needs to be updated?
> > > 
> > > 
> > > Yes it's the json file, but still MirahezeMagic submodule still needs updated in miraheze/mediawiki repo for changes to be live.
> > 
> > 
> > Oh, interesting, and we do that _every_ time we add or delete a MirahezeMagic interface message/override? If _so_, I wasn't aware of that; I was only aware of the RebuildLC maintenance script part. Perhaps @Reception123 can fill me in more on the technicals of the process when he gets up. Anyway, thanks! :)
> 
> Yep it's always been done like that.

Okay, thanks! :)

**Pull request merged**
