### PR TITLE
add miraheze-sidebar-donate message

### PR DESCRIPTION
**Pull request by MrJaroslavik**
is this how it works?

### CODE REVIEW

**Comment by dmehus** [comment]
Since this is for a Miraheze-specific interface message, I'd prefer the `donate` message name be renamed to something like `miraheze-donate`. Also, if a _new_ message is being created, I believe there's one other file that needs to be modified as well.

**Comment by RhinosF1** [comment]
> Since this is for a Miraheze-specific interface message, I'd prefer the `donate` message name be renamed to something like `miraheze-donate`. Also, if a _new_ message is being created, I believe there's one other file that needs to be modified as well.

qqq entry should also be added. We don't always control the name of the message.

**Comment by dmehus** [comment]
> > Since this is for a Miraheze-specific interface message, I'd prefer the `donate` message name be renamed to something like `miraheze-donate`. Also, if a _new_ message is being created, I believe there's one other file that needs to be modified as well.
> 
> qqq entry should also be added. We don't always control the name of the message.

True, but this is for the Miraheze donation link, so it should be a Miraheze-specific donation link, unless there's already a translatewiki.net donate message for `donate`, then yeah, we could just use that and there may already be existing translations for that message.

**Comment by R4356th** [comment]
> > > Since this is for a Miraheze-specific interface message, I'd prefer the `donate` message name be renamed to something like `miraheze-donate`. Also, if a _new_ message is being created, I believe there's one other file that needs to be modified as well.
> > 
> > 
> > qqq entry should also be added. We don't always control the name of the message.
> 
> True, but this is for the Miraheze donation link, so it should be a Miraheze-specific donation link, unless there's already a translatewiki.net donate message for `donate`, then yeah, we could just use that and there may already be existing translations for that message.

The entry for qqq should use the ``Identical`` template proved by TWN.

**Comment by dmehus** [comment]
> > > > Since this is for a Miraheze-specific interface message, I'd prefer the `donate` message name be renamed to something like `miraheze-donate`. Also, if a _new_ message is being created, I believe there's one other file that needs to be modified as well.
> > > 
> > > 
> > > qqq entry should also be added. We don't always control the name of the message.
> > 
> > 
> > True, but this is for the Miraheze donation link, so it should be a Miraheze-specific donation link, unless there's already a translatewiki.net donate message for `donate`, then yeah, we could just use that and there may already be existing translations for that message.
> 
> The entry for qqq should use the `Identical` template proved by TWN.

@R4356th, oh, is there already a generic `donate` message on translatewiki.net? I hadn't looked for that yet.

**Comment by R4356th** [comment]
> > The entry for qqq should use the `Identical` template proved by TWN.
> 
> @R4356th, oh, is there already a generic `donate` message on translatewiki.net? I hadn't looked for that yet.

See https://translatewiki.net/wiki/Template:Identical/Donate.

**Comment by dmehus** [comment]
> > > The entry for qqq should use the `Identical` template proved by TWN.
> > 
> > 
> > @R4356th, oh, is there already a generic `donate` message on translatewiki.net? I hadn't looked for that yet.
> 
> See https://translatewiki.net/wiki/Template:Identical/Donate.

Ah, interesting. So essentially, `MediaWiki:Donate` references `Template:Identical/Donate`, which then lists the various, more-specific donation messages for translation?

**Comment by dmehus** [comment]
Would still prefer this be renamed to `miraheze-donate-sidebar` for consistency with `miraheze-donate`, but it seems fine as is, so :+1:

**Comment by RhinosF1** [comment]
> Would still prefer this be renamed to `miraheze-donate-sidebar` for consistency with `miraheze-donate`, but it seems fine as is, so 👍

It's litterally the word "Donate". I can't see the issue.

**Comment by R4356th** [comment]
> > > > The entry for qqq should use the `Identical` template proved by TWN.
> > > 
> > > 
> > > @R4356th, oh, is there already a generic `donate` message on translatewiki.net? I hadn't looked for that yet.
> > 
> > 
> > See https://translatewiki.net/wiki/Template:Identical/Donate.
> 
> Ah, interesting. So essentially, `MediaWiki:Donate` references `Template:Identical/Donate`, which then lists the various, more-specific donation messages for translation?

Yeah, the concept is correct. Basically, translators will be shown a help message containing the different messages that have been manually listed by others.

**Comment by dmehus** [comment]
> > > > > The entry for qqq should use the `Identical` template proved by TWN.
> > > > 
> > > > 
> > > > @R4356th, oh, is there already a generic `donate` message on translatewiki.net? I hadn't looked for that yet.
> > > 
> > > 
> > > See https://translatewiki.net/wiki/Template:Identical/Donate.
> > 
> > 
> > Ah, interesting. So essentially, `MediaWiki:Donate` references `Template:Identical/Donate`, which then lists the various, more-specific donation messages for translation?
> 
> Yeah, the concept is correct. Basically, translators will be shown a help message containing the different messages that have been manually listed by others.

Okay, thanks. SGTM then.

**Comment by Universal-Omega** [comment]
What's wrong with the already existing message for Donate?

**Comment by RhinosF1** [comment]
> What's wrong with the already existing message for Donate?
> 
> https://github.com/miraheze/MirahezeMagic/blob/6e0706d3b3d5a986097f3408ae9c97067709a5a8/i18n/miraheze/en.json#L15

It's the header of the sidebar that they want to set rather than the message.

**Comment by Universal-Omega** [comment]
> > What's wrong with the already existing message for Donate?
> > https://github.com/miraheze/MirahezeMagic/blob/6e0706d3b3d5a986097f3408ae9c97067709a5a8/i18n/miraheze/en.json#L15
> 
> It's the header of the sidebar that they want to set rather than the message.

Again though, what's wrong with using that message for it?

**Comment by RhinosF1** [comment]
> > > What's wrong with the already existing message for Donate?
> > > https://github.com/miraheze/MirahezeMagic/blob/6e0706d3b3d5a986097f3408ae9c97067709a5a8/i18n/miraheze/en.json#L15
> > 
> > 
> > It's the header of the sidebar that they want to set rather than the message.
> 
> Again though, what's wrong with using that message for it?

Because that says "Donate to Miraheze" like the link but this is just "Donate"

**Comment by Universal-Omega** [comment]
> > > > What's wrong with the already existing message for Donate?
> > > > https://github.com/miraheze/MirahezeMagic/blob/6e0706d3b3d5a986097f3408ae9c97067709a5a8/i18n/miraheze/en.json#L15
> > > 
> > > 
> > > It's the header of the sidebar that they want to set rather than the message.
> > 
> > 
> > Again though, what's wrong with using that message for it?
> 
> Because that says "Donate to Miraheze" like the link but this is just "Donate"

Ah, right, then I still think it should be called miraheze-sidebar-donate or something then. Also this should be added to qqq.json

**Pull request merged**
