### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by magogre**
Add "group page" pages as suggested in https://mediawiki.org/wiki/Manual:User_rights

### CODE REVIEW

**Review by ugochimobi — APPROVED** [review]

**Review by dmehus — COMMENTED** [review]
@magogre This shouldn't be needed, as these are the default local page locations. In any case, I'm actually drafting a PR to create global interface messages for the default user groups, which will include group pages.

**Comment by Universal-Omega** [comment]
I have to agree with @dmehus. Ideally most of these messages should be moved to just metawiki directly since they are only really used there.

**Comment by magogre** [comment]
@Universal-Omega, these messages are also used on commons and other wikis such as template wiki and could be useful there. However, @dmehus if you're already developing a PR for MirahezeMagic, this can be closed then.

**Comment by Universal-Omega** [comment]
No objection to this so merging then. It does no harm.

**Pull request merged**
