### PR TITLE
Remove Meta-specific messages

### PR DESCRIPTION
**Pull request by R4356th**
I do not think Meta should be linked from every Miraheze wiki for user groups like the ones I removed as they can be given to any user by local admins. Those messages should not even be needed for Meta itself as those are added by MW itself. Meta admins can always add those using the MediaWiki namespace if needed.

### CODE REVIEW

**Comment by dmehus** [comment]
This LGTM. I was planning on doing something similar to this in the future, which this PR would not preclude, that would essentially create a `ManageWiki/Default Permissions#group name` group page for each of the default user groups. Included within each blurb would describe the default local user group, link to its local list of permissions, and explain how to create local interface messages that define its local group page location that would override the default.

**Comment by Universal-Omega** [comment]
It was specifically added, and I personally don't see the current need to remove them.

**Comment by Universal-Omega** [comment]
> This LGTM. I was planning on doing something similar to this in the future, which this PR would not preclude, that would essentially create a `ManageWiki/Default Permissions#group name` group page for each of the default user groups. Included within each blurb would describe the default local user group, link to its local list of permissions, and explain how to create local interface messages that define its local group page location that would override the default.

I apologise, but I have absolutely no idea what you mean here...

**Review by Universal-Omega — CHANGES_REQUESTED** [review]
Should these not be removed also?
* grouppage-proxybot
* grouppage-translationadmin

**Comment by R4356th** [comment]
> Should these not be removed also?
> 
> * grouppage-proxybot
> * grouppage-translationadmin

ProxyBot used to enforce NOP but is now defunct. Allowing it to stay that way would probably be good for documentation purposes. As for ``translationadmin``, yeah, good idea.

**Comment by Universal-Omega** [comment]
> > Should these not be removed also?
> > 
> > * grouppage-proxybot
> > * grouppage-translationadmin
> 
> ProxyBot used to enforce NOP but is now defunct. Allowing it to stay that way would probably be good for documentation purposes. As for `translationadmin`, yeah, good idea.

Oh, right about ProxyBot.

**Comment by R4356th** [comment]
```JSON
"group-translator": "Translators",
"group-translator-member": "translator",
"group-translationadmin": "Translation administrators",
"group-translationadmin-member": "translation administrator",
```
Should I remove these, too?

**Comment by Universal-Omega** [comment]
> ```json
> "group-translator": "Translators",
> "group-translator-member": "translator",
> "group-translationadmin": "Translation administrators",
> "group-translationadmin-member": "translation administrator",
> ```
> 
> Should I remove these, too?

I think those can stay.

**Review by Universal-Omega — APPROVED** [review]

**Pull request merged**
