### PR TITLE
Create community portals on wiki creation

### PR DESCRIPTION
**Pull request by AgentIsai**
Per results of RfC on this

### CODE REVIEW

**Comment by Universal-Omega** [comment]
Why can't this just set MediaWiki:Community portal? Technically speaking I am against this as another script. The main page script already has issues, that sometimes cause things to fail, another here will only cause more issues.

**Comment by AgentIsai** [comment]
> Why can't this just set MediaWiki:Community portal? Technically speaking I am against this as another script. The main page script already has issues, that sometimes cause things to fail, another here will only cause more issues.

What do you mean by setting MediaWiki:Community portal?

**Comment by Universal-Omega** [comment]
> > Why can't this just set MediaWiki:Community portal? Technically speaking I am against this as another script. The main page script already has issues, that sometimes cause things to fail, another here will only cause more issues.
> 
> What do you mean by setting MediaWiki:Community portal?

Nevermind, I wasn't thinking straight. I will see if I can think of a better way to do this as the current way with a maintenance script I don't necessarily like and will only increase the chances that wiki creation fails assigning rights and creating main page and this page, etc...

**Comment by Universal-Omega** [comment]
Can conflicts be resolved so I can finally try and get this reviewed?

**Comment by Universal-Omega** [comment]
This has been open over a year, has major conflicts, and I'm not sure the best way to do this but I think a better way is part of the loadout wiki project @OAuthority is working on.

**Pull request closed without merging**
