### PR TITLE
Add hook to stop scripts running as root

### PR DESCRIPTION
**Pull request by RhinosF1**

### CODE REVIEW

**Comment by RhinosF1** [comment]
I don't get how my PHP is invalid but this should make things fail if they run as plain root which is what I'm trying to prevent.

**Comment by JohnFLewis** [comment]
This will bring more harm than benefit. This is the wrong solution to a problem.

**Comment by RhinosF1** [comment]
> This will bring more harm than benefit. This is the wrong solution to a problem.

I've tried politely asking SRE a million and one times. It's tiring.

**Comment by JohnFLewis** [comment]
I do not believe you have, I recall this email and that’s all in the past several months.

**Comment by RhinosF1** [comment]
> I do not believe you have, I recall this email and that’s all in the past several months.

I made numerous requests on IRC, Am sure I can find at least 1 phab task and I checked the timing of today's file I found and my email. It was after my email.

**Comment by JohnFLewis** [comment]
If you don’t feel your concerns are being address appropriately, Reception is the person to approach rather than your current attitude and making these changes which would be more harmful than good by limiting quick and immediate action by anyone of higher level than MWE.

**Comment by RhinosF1** [comment]
> If you don’t feel your concerns are being address appropriately, Reception is the person to approach rather than your current attitude and making these changes which would be more harmful than good by limiting quick and immediate action by anyone of higher level than MWE.

-u www-data

**Comment by JohnFLewis** [comment]
Refer back to my last message about attitude.

**Comment by RhinosF1** [comment]
> Refer back to my last message about attitude.

As soon as I can find a manager in my line on IRC and am around, it'll be discussed.

**Comment by Reception123** [comment]
A new email has been sent by RhinosF1 to sre@ and right now asking everyone to remember to leave things www-data. I don't think this full coercive ban on using root when running stuff on mw* is very appropriate and would very much prefer this issue to be resolved sensibly rather than having to resort to this method.

**Pull request closed without merging**
