### PR TITLE
Update MirahezeMagic

### PR DESCRIPTION
**Pull request by AlvaroMolinaCL**
I have added new translations (Spanish) and definitions (English) in MirahezeMagic:

Addition of "Member" Permission Translation. Note that here I added the name of the plural permission, since by default only the name was shown in the singular. I hope you understand.

Addition of Translation for "centralauth-autoaccount" right. Thanks.

### CODE REVIEW

**Comment by Reception123** [comment]
There might be an error, but the "centralauth-autoaccount" right is already defined by the CentralAuth extension https://translatewiki.net/wiki/MediaWiki:Right-centralauth-autoaccount/es but doesn't seem defined for the actual i18n, es.json

**Comment by AlvaroMolinaCL** [comment]
Although the translations are available in translatewiki.net, they are not reflected in the Special:ListGroupRights, appearing only "centralauth-autoaccount (centralauth-autoaccount)" in the list.

**Comment by Reception123** [comment]
I know, that is what I said. I have made a support desk thread at translatewiki.net

**Comment by AlvaroMolinaCL** [comment]
These problems are quite frequent in non-WMF wikis, this also happens with some translations related to the FlaggedRevs extension. I do not know exactly how translatewiki.net translations are synchronized between wikis, but I think the only ones that have "almost instant" synchronization are WMF wikis and the other wikis have to do another procedure, which I do not know.

**Comment by AlvaroMolinaCL** [comment]
@Reception123: If it is a problem, you could remove the line momentarily so you do not leave the other changes on hold. You think?

**Comment by AlvaroMolinaCL** [comment]
I've removed that line of code until it solves what translatewiki.net (something that can take thousands of decades). For now I want to merge the rest of the changes so they are not stuck.

**Comment by Reception123** [comment]
@AlvaroMolinaCL The "stable-log" translations are already available here: https://github.com/wikimedia/mediawiki-extensions-FlaggedRevs/blob/master/i18n/flaggedrevs/es.json#L171

**Comment by AlvaroMolinaCL** [comment]
Removed.

**Pull request merged**
